// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackerApp;

#nullable disable

namespace TrackerApp.Migrations
{
    [DbContext(typeof(TrackerAppDbContext))]
    [Migration("20250403171658_Changed_DailySummaries_table_design")]
    partial class Changed_DailySummaries_table_design
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrackerApp.Models.DailySummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AwayDuration")
                        .HasColumnType("int");

                    b.Property<int?>("BreakDuration")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StatusDate")
                        .HasColumnType("date");

                    b.Property<int?>("WorkingDuration")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DailySummaries");
                });

            modelBuilder.Entity("TrackerApp.Models.StatusActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DailySummaryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("DailySummaryId");

                    b.ToTable("StatusActivities");
                });

            modelBuilder.Entity("TrackerApp.Models.StatusActivity", b =>
                {
                    b.HasOne("TrackerApp.Models.DailySummary", "DailySummary")
                        .WithMany("StatusActivities")
                        .HasForeignKey("DailySummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailySummary");
                });

            modelBuilder.Entity("TrackerApp.Models.DailySummary", b =>
                {
                    b.Navigation("StatusActivities");
                });
#pragma warning restore 612, 618
        }
    }
}
